title: Casey Chen
author: ''
email: kc.khchen@gmail.com
description: Archive of my thoughts and notes.
baseurl: '/blog'
url: 'https://kckhchen.com'
github_username: kckhchen
rss: RSS
permalink: /:title/

show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
