title: Casey Chen
author: "Casey Chen"
email: kc.khchen@gmail.com
description: Follow my journey on learning new things.
baseurl: "/blog"
url: "https://kckhchen.com"
github_username: kckhchen
rss: RSS
permalink: /:title/
timezone: Asia/Taipei

show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

paginate: 10
paginate_path: "/page:num/"

defaults:
  - scope: { path: "", type: posts }
    values:
      toc: true
